version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: ./deployment/Dockerfile.api
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./docs:/app/docs
      - ./.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    command: uvicorn app.api:app --host 0.0.0.0 --port 8000 --reload
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:80"
    volumes:
      - ./client:/app
      - /app/node_modules
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - VITE_API_ENDPOINT=http://0.0.0.0:8000/seller/
      - NODE_ENV=development
    depends_on:
      - api

networks:
  default:
    driver: bridge